### ISSUE TITLE
intelmqcli: when creating a ticket, please attach the CSV file

### ISSUE THREAD

**Issue by aaronkaplan** [certat/intelmq#3]
So far, at cert.at we always attach the data (CSV file) to the investigation. So, it really is a MIME attachment and not inline text. We should stay consistent here IMHO.

**Comment by sebix** [comment]
I don't understand the issue here. The relevant lines are attached to the incident report in csv-syntax as attachment (comment in RT).

As far as I understood the current setupt, the mailer component in RTIT then attaches this file to the mail. intelmqcli has no connection to the mail itself or MIME.

**Comment by aaronkaplan** [comment]
Ahm. I ll show you directly. It's easier. 

---

Mobile

**Comment by sebix** [comment]
Should have been fixed by 26c69767aed164dd72d8c59a5537fa65acc53e53, please reopen otherwise.
